[2024-03-07 15:26:34.032] learner started
[2024-03-07 15:26:34.033] Initializing model
[2024-03-07 15:26:35.167] Model type: mlp(16, 5)
[2024-03-07 15:26:35.167] Model size: 7015 variables
[2024-03-07 15:26:35.270] Initial checkpoint: ./Checkpoints/test_board_az/checkpoint-0
[2024-03-07 15:26:35.273] 
===================== Exception caught =====================
Traceback (most recent call last):
  File "/home/ultraman287/2024/generalized_chess/./open_spiel/python/algorithms/alpha_zero/alpha_zero.py", line 174, in _watcher
    return fn(config=config, logger=logger, **kwargs)
  File "/home/ultraman287/2024/generalized_chess/./open_spiel/python/algorithms/alpha_zero/alpha_zero.py", line 464, in learner
    num_trajectories, num_states = collect_trajectories()
  File "/home/ultraman287/2024/generalized_chess/./open_spiel/python/algorithms/alpha_zero/alpha_zero.py", line 428, in collect_trajectories
    n = trajectory.states[index]
IndexError: list index out of range

============================================================
[2024-03-07 15:26:35.273] learner exiting
